### ISSUE TITLE
Bone collections disappear with new UI update (on Blender 4.0.2)

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#155]
This issue causes the bone collections to disappear from the UI, and to send an error message when switching between outfits. When going to configuration mode everything bellow the armature tab is also gone.

Just changing/hiding outfit parts gives error message as result:
"Python: Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\MustardUI\outfits\ops_visibility.py", line 63, in execute
    outfit_armature_layers = [x for x in arm.collections_all if x.MustardUI_ArmatureBoneCollection.outfit_switcher_enable and x.MustardUI_ArmatureBoneCollection.outfit_switcher_collection != None]
AttributeError: 'Armature' object has no attribute 'collections_all'. Did you mean: 'collections'?"

Had to downgrade to version 0.31.0.5 to fix the issue.

I know this update is meant for Blender 4.1, but that version is still not out outside of beta candidates until late march, and many people will still wait some time to upgrade to the newer Blender version so it's something to keep in mind that this error will probably show to a lot of people waiting to switch.

**Comment by Mustard2** [comment]
Hi!

I am aware of the problem. Unfortunately Blender keeps changing the API, it's not something I have any control on. :(

I added a check on the update function for the Blender version, to solve these issues in the future. But it's available only from the most recent version and thus it can't inform the user about this issue this time.

I always put the minimum Blender version on the download link of the addon, in this case the minimum version is Blender 4.1 exactly for this issue. I would suggest people to wait updating MustardUI if they stick with Blender 4.0.

**Comment by Mustard2** [comment]
Ok I managed to fix this issue. I will deprecate the fix in 0.32.0, i.e., that future version will not work in Blender 4.0.x.
For now, 0.31.1 should work fine also with Blender 4.0.x with this fix. :)
